aitool/urls.py
from django.urls import path
from .views import register, reg_success, login_user,handle_login_page,otp_verification,page,courses,home,askques

app_name = 'aitool'

urlpatterns = [
    path('reg/', register, name='register'),
    path('reg-success/<str:success_type>/<str:username>/', reg_success, name='reg_success'),
    path('login/', login_user, name='login'),
     path('login-page/', handle_login_page, name='login_page'),
     #path('send-otp-email/', send_otp_email, name='send_otp_email'),
     path('otp-verification/', otp_verification, name='otp_verification'),
     path('chat/', page , name = 'chat'),
    path('courses/',courses, name = 'courses'),
    path('home/<str:username>/',home, name = 'home'),
    path('ask_qns_from_pdf/',askques, name = 'ask_qns_from_pdf' ),

]

jugaad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('aitool.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aitool/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    SKILL_CHOICES = [
        ('C', 'C'),
        ('C++', 'C++'),
        ('Java', 'Java'),
        ('Python', 'Python'),
        ('JavaScript', 'JavaScript'),
        ('React', 'React'),
        ('R', 'R'),
        ('Haskell', 'Haskell'),
        ('SQL', 'SQL'),
        ('HTML_CSS', 'HTML and CSS'),
        ('PHP', 'PHP'),
    ]

    INTEREST_CHOICES = [
        ('Development', 'Development'),
        ('AI_ML', 'Artificial Intelligence and Machine Learning'),
        ('DBA', 'DBA (Database Administrator)'),
        ('Testing_Automation', 'Testing and Automation'),
        ('Research', 'Research Field'),
        ('UI_UX', 'UI/UX Designer'),
        ('Cyber_Security', 'Cyber Security Engineer'),
        ('IoT', 'Internet of Things (IOT)'),
        ('Data_Mining', 'Data Mining'),
        ('Data_Science', 'Data Science'),
    ]
    email_regex = RegexValidator(
        regex=r'^[a-zA-Z0-9_.+-]+@(gmail\.com|yahoo\.com)$',
        message="Email must be a valid Gmail or Yahoo address.",
    )
    
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    email = models.EmailField(default='default@example.com', validators=[email_regex])
    dob = models.DateField()
    education = models.CharField(max_length=100)
    specialization = models.CharField(max_length=100)
    skills = models.CharField(max_length=200, choices=SKILL_CHOICES, blank=True, null=True)
    interests = models.CharField(max_length=200, choices=INTEREST_CHOICES, blank=True, null=True)
    university = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    
    def __str__(self):
        return f"{self.username} - {self.dob.strftime('%Y-%m-%d')}"
    

'''class LoginForm(models.Model):
    username = models.CharField(max_length=50, required=True)
    password = models.CharField(widget=PasswordInput(), required=True)
    accept_terms = models.BooleanField(required=True)'''

    

aitool/forms.py
# forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import UserProfile

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['username', 'password', 'name', 'dob', 'education', 'specialization', 'university', 'email']
        widgets = {
            'password': forms.PasswordInput(),
            'dob': forms.DateInput(attrs={'type': 'date'}),
        }

    skills = forms.MultipleChoiceField(choices=UserProfile.SKILL_CHOICES, widget=forms.CheckboxSelectMultiple, required=False)
    interests = forms.MultipleChoiceField(choices=UserProfile.INTEREST_CHOICES, widget=forms.CheckboxSelectMultiple, required=False)

    def clean_skills(self):
        skills = self.cleaned_data.get('skills')
        return ",".join(skills) if skills else None

    def clean_interests(self):
        interests = self.cleaned_data.get('interests')
        return ",".join(interests) if interests else None

    def clean(self):
        cleaned_data = super().clean()
        # Ensure that skills and interests are saved in the model fields
        cleaned_data['skills'] = cleaned_data.get('skills')
        cleaned_data['interests'] = cleaned_data.get('interests')
        return cleaned_data
    
    email_regex = RegexValidator(
        regex=r'^[a-zA-Z0-9_.+-]+@(gmail\.com|yahoo\.com|srmap\.edu\.in)$',
        message="Email must be a valid Gmail or Yahoo address or SRMAP Gmail address.",
    )
    email = forms.EmailField(validators=[email_regex])


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    

aitool/views.py
# aitool/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import RegistrationForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.utils.crypto import get_random_string
from django.conf import settings
from django.contrib.auth import get_user_model
from datetime import datetime
from django.http import JsonResponse
import requests
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from .models import UserProfile
from PyPDF2 import PdfReader
from io import BytesIO

# Step 1: Collect user profiles and interests
user_profiles = UserProfile.objects.all()

# Step 2: Preprocess data
interests = [profile.interests for profile in user_profiles]

# Step 3: Convert interests to numerical vectors
vectorizer = TfidfVectorizer()
interests_matrix = vectorizer.fit_transform(interests)


User = get_user_model()


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # Store the form data in the session
            request.session['username'] = form.cleaned_data['username']
            request.session['password'] = form.cleaned_data['password']
            request.session['name'] = form.cleaned_data['name']
            request.session['dob'] = form.cleaned_data['dob'].isoformat()
            request.session['education'] = form.cleaned_data['education']
            request.session['specialization'] = form.cleaned_data['specialization']
            request.session['university'] = form.cleaned_data['university']
            request.session['email'] = form.cleaned_data['email']
            request.session['skills'] = form.cleaned_data['skills']
            request.session['interests'] = form.cleaned_data['interests']

            # Save the form data to the database
            user_profile = form.save(commit=False)
            user_profile.skills = form.cleaned_data['skills']
            user_profile.interests = form.cleaned_data['interests']
            print(user_profile.skills)
            #user_profile.save()

            # Send OTP email
            email = form.cleaned_data['email']
            otp = get_random_string(length=6, allowed_chars='1234567890')
            subject = 'Your OTP for Registration'
            message = f"Hi {user_profile.username},\n\nThe OTP is to confirm your registration in our Aitool student portal.\n\nThe OTP: {otp}\n\nIf you want to register successfully, click the given OTP in the OTP verification site.\n\nFrom,\nAitool"
            from_email = 'eswaryelur13@gmail.com'
            recipient_list = [email]
            send_mail(subject, message, from_email, recipient_list)

            # Store OTP in session for verification
            request.session['otp'] = otp

            # Redirect to OTP verification page
            return redirect('aitool:otp_verification')

    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})



def login_user(request):
    login_unsuccessful = False
    username = None  # Initialize the variable

    if request.method == 'POST':
        form = LoginForm(request.POST)
        print(form.errors)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            print(username)

            try:
                user_profile = UserProfile.objects.get(username=username)
            except UserProfile.DoesNotExist:
                login_unsuccessful = True
            else:
                if password == user_profile.password:
                    login_unsuccessful = False
                    return redirect('aitool:reg_success', success_type='login', username=username)
                else:
                    login_unsuccessful = True

    else:
        form = LoginForm()

    # Check if the page is reloaded, set username to None and login_unsuccessful to False
    if request.method == 'GET' and request.session.get('login_reloaded'):
        request.session['login_reloaded'] = False  # Reset the session variable
        return render(request, 'login.html', {'form': form, 'login_unsuccessful': False, 'username': username})

    return render(request, 'login.html', {'form': form, 'login_unsuccessful': login_unsuccessful, 'username': username})



# In your view where you handle the login page load (GET request), set the session variable
def handle_login_page(request):
    request.session['login_reloaded'] = True
    return render(request, 'login.html', {'form': LoginForm()})




#@login_required(login_url='register')

def reg_success(request, success_type,username=None):
    success_messages = {
        'registration': 'Registration Successful!',
        'login': 'Login Successful!',
    }
    success_message = success_messages.get(success_type, 'Unknown Action')

    return render(request, 'success.html', {'success_message': success_type,'username':username})




def otp_verification(request):
    user_email = request.session.get('email', '')
    form = RegistrationForm()
    dob_str = request.session.get('dob')
    dob_date = datetime.strptime(dob_str, '%Y-%m-%d').date() if dob_str else None   

    if request.method == 'POST':
        entered_otp = request.POST.get('otp')

        # Retrieve OTP from session
        stored_otp = request.session.get('otp')
        print(entered_otp)
        print(stored_otp)

        if stored_otp and entered_otp == stored_otp:
            # OTP verification successful
            form_data = {
                'username': request.session.get('username'),
                'password': request.session.get('password'),
                'name': request.session.get('name'),
                'dob': dob_date,
                'education': request.session.get('education'),
                'specialization': request.session.get('specialization'),
                'university': request.session.get('university'),
                'email': user_email,
               'skills': request.session.get('skills').split(','),  # Ensure skills is a list
             'interests': request.session.get('interests').split(','),

            }

            form = RegistrationForm(form_data,files=request.FILES)
            print(form_data)
            print(form.is_valid())
            print(form.errors)

            if form.is_valid():
                # Save the form data to the database
                user_profile = form.save(commit=False)
                user_profile.skills = form.cleaned_data['skills']  # Set skills from form
                user_profile.interests = form.cleaned_data['interests'] 
                user_profile.save()
                # Redirect to a success page with registration type
                return redirect('aitool:reg_success', success_type='registration', username=user_profile.username)

        else:
            # Display an error message for invalid OTP
            error_message = 'Invalid OTP. Please enter the correct OTP.'
            return render(request, 'verify_otp.html', {'form': form, 'email': user_email, 'error_message': error_message})

    return render(request, 'verify_otp.html', {'form': form, 'email': user_email})

def char_with_gpt(prompt):
    url = 'https://api.openai.com/v1/chat/completions'
    headers = {
        'Authorization': 'Bearer OpenAI_API_key',  # Replace with your OpenAI_API_key with actual key
        'Content-Type': 'application/json'
    }

    payload = {
        'model': 'gpt-3.5-turbo',
        'messages': [
            {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(url, headers=headers, json=payload)
    response_json = response.json()

    # Accessing the content of the generated message
    generated_content = response_json['choices'][0]['message']['content']
    return generated_content


def page(request):
    if request.method == 'POST':
        print(request.POST)
        user_input = request.POST['user_input']
        print(user_input)
        response = char_with_gpt(user_input)
        return render(request, 'landing.html', {'answer': response})

    return render(request, 'landing.html')
def courses(request):
    """
    View function to handle the course search request.
    """
    if request.method == 'POST':
        # Retrieve the course query from the form
        query = request.POST.get("course")+"courses"
        platforms=['udemy','coursera']
        generated_quries=[query+platform for platform in platforms]
        links=[]
        print(links)
        # Perform Google search
        for q in generated_quries:
            l = search_google(q)
            links.extend(l)
        
        return render(request,'courses.html',{'links':links})
    else:
        # Render the course search form
        return render(request, 'courses.html')
    

def search_google(query):
    api_key=open(r"C:\users\abhigna\Desktop\hackathon\demo\creds.txt",'r').readlines()[0] # API_KEY
    search_engine_id=open(r"C:\users\abhigna\Desktop\hackathon\demo\creds.txt",'r').readlines()[1]

    search_query=query
    url='https://www.googleapis.com/customsearch/v1'
    params={
    'q':search_query,
    'key':api_key,
    'cx':search_engine_id
    }

    response=requests.get(url,params=params)
    results=response.json()
    links=[]
    if 'items' in results:
        for item in results['items']:
            links.append(item['link'])
    return links
def get_similar_profiles(user_profile):
    user_interests = user_profile.interests

aitool/templates/askques.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Queries</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
/*
            background: url("{% static 'images/hi.jpg' %}") no-repeat center center fixed;
            background-size: cover;;*/
            text-align: center;
            padding: 150px;
            font-family: 'Lato', sans-serif;
        }
        .container {
            padding: 20px; /* Padding on all sides */
            justify-content: center;
        }
        form, .response-box {
/*            background-color: #d4d1d1; /* Grey background */*/
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Shadow effect */
        }
        input[type="text"],
        input[type="file"] {
            margin-bottom: 10px;
        }
        input[type="submit"] {
            background-color: #007bff; /* Blue submit button */
            color: #ffffff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        label
        {
            font-size: 25px;
        }
    </style>
</head>
<body>
    <div class="container my-5">
        <!-- <div class="row my-5"></div> -->
        <!-- <div class="row my-5"></div> -->
        <div class="row my-5">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="ques" class="form-label">Type your question here</label>
                        <input type="text" class="form-control" id="ques" name="ques" placeholder="Type your question here">
                    </div>
                    <div class="mb-3">
                        <label for="pdf_file" class="form-label">Upload a PDF file </label>
                        <input type="file" class="form-control" id="pdf_file" name="pdf_file">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
        {% if request.method == "POST" %}
            <div class="row mt-4">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="response-box">
                        <p><strong>Query asked:</strong> {{ q }}</p>
                        <p><strong>Answer:</strong> {{ ans }}</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    <!-- Bootstrap JS (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-7v+JcEc/uhFZ5tWeMfoj+qpCtf3An8Q+31xdjktZ1I6S3EK6zktC5DkUaDk3n9Xu" crossorigin="anonymous"></script>
</body>
</html>

aitool/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <style>
        body {
            background: url("{% static 'images/nb.jpeg' %}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        #login-card {
            background-color: rgba(255, 255, 255, 0.4);
            padding: 50px;
            border-radius: 10px;
            width: 600px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin-bottom: 10px;
            margin-right: 10px;
        }

        h2 {
            color: black;
            text-align: center;
            margin-bottom: 50px;
            text-decoration: underline;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        .form-group {
            margin-left: 100px;
            margin-bottom: 16px;
        }

        label {
            color: black;
            margin-bottom: 8px;
            margin-right: 50px;
        }

        input,
        textarea {
            padding: 8px;
            border: 1px solid black;
            border-radius: 4px;
            margin-bottom: 10px;
        }

        textarea {
            resize: vertical; /* Allow vertical resizing of textarea */
        }

        #accept-terms {
            margin-bottom: 16px;
        }

        #login-button {
            background-color: lightgrey;
            color: black;
            padding: 8px;
            border: 1px solid black;
            border-radius: 4px;
            margin-left: 250px;
            width: 100px;
            transition: background-color 0.3s ease-in-out;
        }

        #show-password {
            position: relative;
            bottom: 40px;
            margin-left: 280px;
            cursor: pointer;
            color: black;
        }

        #login-button:hover {
            background-color: green;
            color: white;
        }

        p {
            color: red;
            text-align: center;
            margin-top: 50px;
            /* Add margin to create space between login-card and the message */
        }
    </style>
</head>

<body>
    

    <div id="login-card">
        <h2>Login</h2>

        <form method="post" action="{% url 'aitool:login' %}">
            {% csrf_token %}

            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" required>
            </div>

            <div id="password-container" class="form-group">
                <label for="password">Password: </label>
                <input type="password" name="password" id="password" required>
                <span id="show-password" onclick="showPassword()">👀</span>
            </div>

            <div class="form-group" id="accept-terms">
                <input type="checkbox" name="accept-terms" id="accept-terms-checkbox" required>
                <label for="accept-terms-checkbox">I have read and accept all the terms and conditions.</label>
            </div>

            <button id="login-button" type="submit">Login</button>
        </form>
        
        {% if login_unsuccessful %}
            <p style="color: red;">Invalid username or password. Please try again.</p>
        {% endif %}
    
    </div>

    

    <script>
        function showPassword() {
            var passwordField = document.getElementById("password");
            if (passwordField.type === "password") {
                passwordField.type = "text";
            } else {
                passwordField.type = "password";
            }
        }
    </script>

</body>

</html>

aitool/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Register</title>
    <style>
        body {
            background: url("{% static 'images/hi.jpg' %}") no-repeat center center fixed;
            background-size: cover;
            height: 80vh;
            margin: 100px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        #registration-card {
            background-color: rgba(255, 255, 255, 0.4);
            padding: 15px;
            border-radius: 10px;
            width: 400px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: black;
            text-align: center;
            margin-bottom: 10px;
            text-decoration: underline;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        .form-group {
            margin-bottom: 16px;
        }

        label {
            color: black;
            margin-bottom: 8px;
            margin-right: 50px;
        }

        input,
        textarea {
            padding: 8px;
            border: 1px solid black;
            border-radius: 4px;
            margin-bottom: 10px;
        }

        textarea {
            resize: vertical; /* Allow vertical resizing of textarea */
        }

        #password-container {
            position: relative;
        }

        #show-password {
            position: absolute;
            top: 3px;
            right: 100px;
            cursor: pointer;
            color: black;
        }

        #register-button {
            background-color: lightgrey;
            color: black;
            padding: 8px;
            border: 1px solid black;
            border-radius: 4px;
            transition: background-color 0.3s ease-in-out;
        }

        #register-button:hover {
            background-color: green;
            color: white;
        }
    </style>
</head>

<body>

    <div id="registration-card">
        <h2>Register</h2>

        <form method="post" action="{% url 'aitool:register' %}">
            {% csrf_token %}

            {% if form.errors %}
            <p id="error-message" style="color: red;">{{ form.errors.username }}</p>
            {% endif %}

            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" required>
            </div>

            <div id="password-container" class="form-group">
                <label for="password">Password: </label>
                <input type="password" name="password" id="password" required>
                <span id="show-password" onclick="showPassword()">👀</span>
            </div>

            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" name="name" required>
            </div>

            <div class="form-group">
                <label for="dob">Date of Birth:</label>
                <input type="date" name="dob" required>
            </div>

            <div class="form-group">
                <label for="education">Education:</label>
                <input type="text" name="education" required>
            </div>

            <div class="form-group">
                <label for="specialization">Specialization:</label>
                <input type="text" name="specialization" required>
            </div>

            <div class="form-group">
                <label for="university">University:</label>
                <input type="text" name="university" required>
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" name="email" required>
            </div>

            <div class="form-group">
                <label for="skills">Skills:</label>
                <div>
                    <input type="checkbox" name="skills" value="C"> C
                    <input type="checkbox" name="skills" value="C++"> C++
                    <input type="checkbox" name="skills" value="Java"> Java
                    <input type="checkbox" name="skills" value="Python"> Python
                    <input type="checkbox" name="skills" value="JavaScript"> JavaScript
                    <input type="checkbox" name="skills" value="React"> React
                    <input type="checkbox" name="skills" value="R"> R
                    <input type="checkbox" name="skills" value="Haskell"> Haskell
                    <input type="checkbox" name="skills" value="SQL"> SQL
                    <input type="checkbox" name="skills" value="HTML_CSS"> HTML and CSS
                </div>
                <span id="skills-error" style="color: red;"></span>
            </div>

            <div class="form-group">
                <label for="interests">Interests:</label>
                <div>
                    <input type="checkbox" name="interests" value="Development"> Development
                    <input type="checkbox" name="interests" value="AI_ML"> Artificial Intelligence and Machine Learning
                    <input type="checkbox" name="interests" value="DBA"> DBA (Database Administrator)
                    <input type="checkbox" name="interests" value="Testing_Automation"> Testing and Automation
                    <input type="checkbox" name="interests" value="Research"> Research Field
                    <input type="checkbox" name="interests" value="UI_UX"> UI/UX Designer
                    <input type="checkbox" name="interests" value="Cyber_Security"> Cyber Security Engineer
                    <input type="checkbox" name="interests" value="IoT"> Internet of Things (IoT)
                    <input type="checkbox" name="interests" value="Data_Mining"> Data Mining
                    <input type="checkbox" name="interests" value="Data_Science"> Data Science
                </div>
            </div>

            <button id="register-button" type="submit">Register</button>
        </form>
    </div>

    <script>
        function showPassword() {
            var passwordField = document.getElementById("password");
            if (passwordField.type === "password") {
                passwordField.type = "text";
            } else {
                passwordField.type = "password";
            }
        }
    </script>

</body>

</html>

aitool/templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Registration Success</title>
    <style>
        body {
            background: url("{% static 'images/hi.jpg' %}") no-repeat center center fixed;
            background-size: cover;;
            text-align: center;
            padding: 150px;
            font-family: 'Lato', sans-serif;
        }

        #success-message {
            color: #4CAF50;
            font-size: 50px;
            margin-bottom: 20px;
        }

        p {
            font-size: 20px;
            color: #333;
            margin-bottom: 40px;
        }

        #back-button {
            background: #2196F3;
            color: white;
            padding: 15px 30px;
            text-decoration: none;
            border-radius: 8px;
            font-size: 25px;
            margin-top: 30px;
            display: inline-block;
        }

        #back-button:hover {
            background: #0c7cd5;
        }

        #navigation {
            margin-top: 50px;
        }

        #navigation a {
            text-decoration: none;
            color: #fff;
            margin: 0 20px;
            font-size: 25px;
            transition: color 0.3s ease-in-out;
        }

        #navigation a:hover {
            color: #1aea2b;
        }
    </style>
</head>
<body>
    <h1 id="success-message" class="my-5">{{ success_message|title }} Successful</h1>
    <br>
    <h3 class="my-3">Thank you, {{ username }}, for your {{ success_message }}.</h3>
    <br><br><br>
    <div id="navigation" class="my-5">
        <a href="{% url 'aitool:ask_qns_from_pdf' %}" class="btn btn-primary">Ask a Question</a>
        <a href="{% url 'aitool:courses'  %}" class="btn btn-primary">Search Courses</a>
        <a href="{% url 'aitool:home' username %}" class="btn btn-primary">Find Similar Interests</a>
        <a href="{% url 'aitool:chat' %}" class="btn btn-primary">Chat with AI Instructor</a>
    </div>

    <!-- <a href="{% url 'aitool:home' username %}" id="back-button">Back to Home</a> -->
</body>
</html>